### ISSUE TITLE
STL file dimensions

### ISSUE THREAD

**Issue by okwichu** [starmatt/Starry58#1]
Hi, I tried to print these files at `i.materialize`, but the website autodetected the files at a size that can't possibly be correct (see attachment):
 
![CleanShot 2022-10-13 at 08 25 23](https://user-images.githubusercontent.com/117988/195639051-29c020d1-d714-4f5b-8db8-bf831023c953.png)

Can you add instructions for what size to set the dimensions at?

**Comment by okwichu** [comment]
For reference, the [BoardSodie](https://github.com/BoardSodie/Lily58-Acrylic-Case) case gets laser cut at Ponoko with width 13.83 in, height 15.03 in, and a height of 0.12 inches.

![CleanShot 2022-10-13 at 08 26 37](https://user-images.githubusercontent.com/117988/195639564-1056cceb-19d5-4494-a268-c93b1eda8d79.png)

**Comment by starmatt** [comment]
Hello, these numbers are right but the unit should be millimeters, not inches ! Check if you can change the unit on the materialize website.

**Comment by okwichu** [comment]
Thanks!

On October 15, 2022, JasonA ***@***.***> wrote:
> Hello, these numbers are right but the unit should be millimeters, not
> inches ! Check if you can change the unit on the materialize website.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/starmatt/Starry58/issues/1#issuecomment-1279698109>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAA4ZZFCJ3TE2WWFFSNFF3TWDJVZJANCNFSM6AAAAAAREMXSME>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
